DROP DATABASE IF EXISTS QA;
CREATE DATABASE QA;
USE QA;

CREATE TABLE questions (
  _id INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  product_id INT NOT NULL,
  body VARCHAR(1000) NOT NULL,
  askerName VARCHAR(100) NOT NULL,
  reported BOOLEAN NOT NULL,
  createdAt VARCHAR(100) NOT NULL,
  helpfulness INT NOT NULL
);

CREATE TABLE answers (
  _id INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  question_id INT NOT NULL,
  body VARCHAR(1000) NOT NULL,
  answererName VARCHAR(100) NOT NULL,
  reported BOOLEAN NOT NULL,
  createdAt VARCHAR(100) NOT NULL,
  helpfulness INT NOT NULL
  FOREIGN KEY(question_id) REFERENCES questions(_id)
);

CREATE TABLE photos  (
  _id INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  URL VARCHAR(3000) NOT NULL, 
  FOREIGN KEY(answer_id) REFERENCES answers(_id)
);


