DROP DATABASE IF EXISTS QA;
CREATE DATABASE QA;
\c QA;

CREATE TABLE questions (
  id INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  product_id INT NOT NULL,
  body VARCHAR(1000) NOT NULL,
  date_written VARCHAR(100) NOT NULL,
  asker_name VARCHAR(100) NOT NULL,
  asker_email VARCHAR(100) NOT NULL,
  reported BOOLEAN NOT NULL,
  helpful INT NOT NULL
);

CREATE TABLE answers (
  id INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  question_id INT NOT NULL,
  body VARCHAR(1000) NOT NULL,
  date_written VARCHAR(100) NOT NULL,
  answerer_name VARCHAR(100) NOT NULL,
  answerer_email VARCHAR(100) NOT NULL,
  reported BOOLEAN NOT NULL,
  helpful INT NOT NULL
  CONSTRAINT answers_id
    FOREIGN KEY(question_id)
      REFERENCES questions(id)
);

CREATE TABLE photos (
  id INT UNIQUE PRIMARY KEY NOT NULL AUTO_INCREMENT,
  url VARCHAR(3000) NOT NULL,
  answer_id INT NOT NULL,
  CONSTRAINT photos_id
    FOREIGN KEY(answer_id)
      REFERENCES answers(id)
);


